name: churn_model
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.x'
      - uses: actions/setup-node@v3
        with:
            node-verison: '16'
      - uses: iterative/setup-cml@v1


      - name: prepare environment
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
            python script.py

      - name: Generate Report
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "## Metrics" > report.md
            cat metrics.txt >> report.md

            echo "## Confusion Matrics" >> report.md
            echo "![](./conf_matrix.png)" >> report.md

            cml comment create report.md
            